### ISSUE TITLE
Incompatible version of Scala

### ISSUE THREAD

**Issue by zaccharieramzi** [H4ml3t/spark-scala-maven-boilerplate-project#1]
Hi ,

I'm currently trying to start a Spark project using eclipse. In order for it to be deployed on a real spark cluster I wanted to build it with maven that's why I downloaded your boilerplate and I thank you for that.

However I have two errors occuring when I import this project in Eclipse via "import as existing Maven project". Indeed the IDE gives me two errors and I think they are somehow related :
- Many libraries are marked as cross-compiled with an incompatible version of Scala (akka_actor, akka_remote, chill -which btw I don't need -, spark, json). Moreover when I added the breeze library it said the same thing whereas if I do it outside a Maven project I don't have any problem : 
  spark-core_2.10-1.2.0-cdh5.3.1.jar of spark-scala-maven-boilerplate-project-master build path is cross-compiled with an incompatible version of Scala (2.10.0). In case this report is mistaken, this check can be disabled in the compiler preference page.
- The compiler cannot find the main class :
  Error: Could not find or load main class com.examples.MainExample.

I'm using Eclipse Juno, Java 1.6 and Scala 2.11.6(I think that's where the problem is).

I tried understanding this issue : https://github.com/sonatype/m2eclipse-scala/issues/30 but I didn't get it (I'm a newbie in Maven).

Can you give me some hints on how to fix these issues. Thank you in advance.

**Comment by meniluca** [comment]
Hi,
please try to update these values

```
<scala.tools.version>2.11</scala.tools.version>
<scala.version>2.11.6</scala.version>
```

and 

```
<dependency>
   <groupId>org.apache.spark</groupId>
   <artifactId>spark-core_2.11</artifactId>
   <version>1.2.0-cdh5.3.0</version>
</dependency>
```

compatibly with the spark version you have in the cluster. Run `spark-shell` to see the version your cluster is using and double check the corresponding library is present in the cloudera maven repository here: https://repository.cloudera.com/cloudera/repo/org/apache/spark/spark-core_2.11/

Let me know,
L

**Comment by zaccharieramzi** [comment]
Thank you for your quick answer .

So actually the cluster on which I'm going to work is using the 1.2.0 version of Spark (that's good), and the 2.10.4 version of Scala. Do you think it's going to be a problem ?

I tried to update the values you gave me but it now returns me this error : 
Missing artifact org.apache.spark:spark-core_2.11:jar:1.2.0-cdh5.3.0    pom.xml
which goes along with this one : 
'/home/zaccharie/.m2/repository/org/apache/spark/spark-core_2.11/1.2.0-cdh5.3.0/spark-core_2.11-1.2.0-cdh5.3.0.jar

So I went to check in my files and indeed I don't have this jar (actually it's just a text file saying I don't have this jar...).  It exists in the repository of cloudera but it's an empty directory.
What do you think ? 

Zac

**Comment by meniluca** [comment]
Do you have the scala plugin (and JDK) installed properly? ([like described in this post](https://nosqlnocry.wordpress.com/2015/03/05/setup-eclipse-to-start-developing-in-spark-scala))

In that case I suggest you to (like in the linked article) tune your scala plugin with the same version of your cluster.

Moreover you should use this dependency

```
<dependency>
   <groupId>org.apache.spark</groupId>
   <artifactId>spark-core_2.10</artifactId>
   <version>1.2.0</version>
</dependency>
```

instead of the one previously suggested, and to put back those variable to

```
<scala.tools.version>2.10</scala.tools.version>
<scala.version>2.10.4</scala.version>
```

after you've downgraded to the scala plugin 2.10.4.

Let me know,
L

**Comment by zaccharieramzi** [comment]
Ok so what I had to do was to uninstall eclipse which was to recent to have a 2.10.4 version of the scala IDE. Then I reinstalled the scala 2.10.4 plugin and the M2E plugin on eclipse. 
The problems I had before disappeared but now I'm confronted to 2 new problems which are almost identical : 
Plugin execution not covered by lifecycle configuration: net.alchim31.maven:scala-maven-plugin:3.1.3:compile (execution: default, phase: compile)   pom.xml 
The second one is the same but with test Compile instead of compile.

Do you have any idea what this could be due to I hardly understand what it is saying...
Thank you again for your support !

Edit : I figured it out using an eclipse quick-fix which suggested adding a new m2e connector for lifecycle... Thanks for everything I have no more problem with the basic package !! :)

Zac

**Comment by meniluca** [comment]
Perfect, I'm glad you solved the problem,
sometimes rebuilding the project with maven just with a simple Alt+F5 can solve everything.
See you around!
L

[Closed]

**Comment by zaccharieramzi** [comment]
Again thank you very much.

If I may however, I would like to point out a small mistake you did in the
instructions of the readMe : the name of the file in spark-submit is not
correct. It's easily correctable but at first I didn't understand what was
going on since the names are very close.  You wrote
spark-scala-maven-project-0.0.1-SNAPSHOT-with-depencencies.jar
but actually it's
spark-scala-maven-project-0.0.1-SNAPSHOT-jar-with-dependencies.jar

Cheers,

Zac

2015-05-02 15:21 GMT+02:00 Luca Menichetti notifications@github.com:

**Comment by meniluca** [comment]
Good, that was misspelled.
Now it's corrected, thank you very much for the correction.
Cheers,
L

**Comment by TiXbY** [comment]
Hi Zac,
It seems I am facing the same problem you described above.
Could you detail the resolution: "eclipse quick-fix which suggested adding a new m2e connector for lifecycle..."
Do you recall which plugin you added?
Once I am selecting "Discover new m2e connectors" I get an empty selection.

Thank :-)

**Comment by zaccharieramzi** [comment]
It appears to be "Java 8 support for m2e for Eclipse Kepler" when I look at the installed plugins in the Eclipse marketplace but it doesn't ring any bell so I'm not that sure. 
If you want you can go to Help -> About Eclipse and tell me which plugins are associated with m2e and I can tell you if there is any difference between yours and mine.

**Comment by TiXbY** [comment]
Thanks Zac for being supportive :-)
I don't know what was the problem.
Eventually, I followed the http://scala-ide.org/docs/tutorials/m2eclipse/ guidelines to create Maven projects. It worked for me (at the end).
Cheers,
Yishai

**Comment by meniluca** [comment]
Hi all, sorry for my late reply. I would suggest what @TiXbY was saying, since for me there was no error. Repeating the procedure again in another environment worked as well.
Bye :)
