### ISSUE TITLE
MavenPlugin connectors error

### ISSUE THREAD

**Issue by torp56** [H4ml3t/spark-scala-maven-boilerplate-project#3]
Hi
when I import into Eclipse IDE (Neon.2) I get these errors:

![image](https://cloud.githubusercontent.com/assets/16907125/23708835/a5f4151a-0417-11e7-9c52-202ec317aee5.png)

In pom.xml dependencies editor I see this:
![image](https://cloud.githubusercontent.com/assets/16907125/23708991/34b59fa8-0418-11e7-80bf-9ffba9f7ddbc.png)

Plugin execution not covered by lifecycle configuration: net.alchim31.maven:scala-maven-plugin:3.1.3:compile (execution: default, phase: compile / testCompile)

How do I resolve ?

Regards Erik Torp

**Comment by meniluca** [comment]
Hi @torp56 ,
sorry for replying so late. Have you resolved the issue? I don't have Neon but I guess this skeleton should be updated with new plugin.

Here the link: http://scala-ide.org/download/current.html
which is:  http://download.scala-ide.org/sdk/lithium/e46/scala211/stable/site 
(have a look at the drag and drop installation too)

Let me know :)
Luva
